### ISSUE TITLE
I accidentally rebuilt this. Want to collaborate?

### ISSUE THREAD

**Issue by erikdstock** [epilande/gatsby-theme-auth0#23]
I'd taken the popular gatsby + auth0 post and componentized some of it. Would you be open to pull requests if I find anything to contributed from my as-yet unpublished theme? https://github.com/erikdstock/gatsby-theme-auth0-es

**Comment by epilande** [comment]
Hi @erikdstock, yes of course! Contributions are always welcomed 😄

**Comment by dandv** [comment]
@erikdstock, great to see your [comparison with prior art](https://github.com/erikdstock/gatsby-theme-auth0-ts#comparison-with-gatsby-theme-auth0) in your approach! It's something I've been [advocating for](https://github.com/search?q=comparison+with+author%3Adandv&ref=searchresults&type=Issues&utf8=%E2%9C%93) for years; still boggles my mind how often people reinvent the wheel but don't document how it's better than the previous ones.

One key aspect I'd love to see a collaboration among folks on, is a [security audit](https://github.com/erikdstock/gatsby-theme-auth0-ts/issues/10).

**Comment by erikdstock** [comment]
Agreed - i haven't changed much on my end and haven't had a production use case for this yet, but a security audit among other things would be welcome.
