### ISSUE TITLE
Request: Expose idToken in the AuthService

### ISSUE THREAD

**Issue by monachilada** [epilande/gatsby-theme-auth0#37]
It would be great if the `AuthService` expose the original `idToken` in addition to the `accessToken`. That way I could securely forward this authentication onto my server side app that implements the same secret key as used to set-up my Auth0 application.

For reference, the other famous [useAuth](https://github.com/Swizec/useAuth) hook does this, see the issue here: https://github.com/Swizec/useAuth/issues/11

**Comment by epilande** [comment]
That sounds like a great idea. Not sure when I'll be able to get to it...If you or anyone wants to take a crack at it, I'm open to PRs.

**Comment by devuxer** [comment]
@epilande , Pull request sent. Please let me know if that works.

**Comment by epilande** [comment]
🎉 This has been released with [v1.1.1](https://github.com/epilande/gatsby-theme-auth0/releases/tag/v1.1.1)
